### PR TITLE
simple uefi usability fix

### PR DESCRIPTION
**Pull request by john-clark**
short term fix until keyboard subs can be fixed

### CODE REVIEW

**Comment by mcb30** [comment]
As discussed on IRC, this is not a suitable fix to work around broken UEFI firmwares that don't understand the Ctrl key.

We deliberately leave the watchdog running; if we unconditionally disable it then that would defeat the entire purpose of the watchdog timer.

**Comment by ipxe-devel** [comment]
Matthias Oponczewski will be out of the office starting  24.07.2015 and
will be returning on 17.08.2015.

I will respond to your message when I return.

-------------------------------------------------------------------------
Deutsche B�rse AG
Chairman of the Supervisory Board/
Vorsitzender des Aufsichtsrats:
Dr. Joachim Faber
Executive Board/Vorstand:
Carsten Kengeter,  (Chief Executive Officer/Vorsitzender),
Andreas Preuss (Deputy Chief Executive Officer/
stellv. Vorsitzender),
Gregor Pottmeyer, Hauke Stars, Jeffrey Tessler.
Aktiengesellschaft with registered seat in/mit Sitz in
Frankfurt am Main.
Commercial register/Handelsregister: HRB 32232
Local court/Amtsgericht Frankfurt am Main.

-----------------------------------------
Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte
sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren
dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen
ist nicht gestattet.

The information contained in this message is confidential or protected by
law. If you are not the intended recipient, please contact the sender and
delete this message. Any unauthorised copying of this message or
unauthorised distribution of the information contained herein is prohibited.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

**Comment by hildred** [comment]
I always thought the control-x should have been Esc, the tab and watchdog timer change ideas are not  good but the control-c could be argued either way.

**Comment by dreamcat4** [comment]
Hi there. 9 months later, I boot up the latest ipxe.efi and its still broken. That is on 2 different uefi PCs.

Would have really appreciated if you guys had just merged this, at least for the time being (while it was broke all this time).

**Comment by dreamcat4** [comment]
OK sorry. This has been explained to me properly on IRC now:

 13:57 	<mcb30>	If you are using a USB keyboard, then you can work around the broken UEFI firmware by using iPXE's own USB keyboard driver
13:57 	<mcb30>	(instead of the UEFI keyboard driver)
13:58 	<mcb30>	You can trivially verify the the problem is independent of iPXE by e.g. booting straight into the UEFI shell
13:58 	<mcb30>	You will find that, for example, "Ctrl-C" acts as just "C"

Which is great. It would be even better to know / have documented somewhere (relevant places) how users can do that!

**Comment by ipxe-devel** [comment]
On 07/05/16 16:12, Dreamcat4 wrote:
> OK sorry. This has been explained to me properly on IRC now:
>
> 13:57 If you are using a USB keyboard, then you can work around the
> broken UEFI firmware by using iPXE's own USB keyboard driver
> 13:57 (instead of the UEFI keyboard driver)
> 13:58 You can trivially verify the the problem is independent of iPXE by
> e.g. booting straight into the UEFI shell
> 13:58 You will find that, for example, "Ctrl-C" acts as just "C"
>
> Which is great. It would be even better to know / have documented
> somewhere (relevant places) how users can do that!

You could also try this patch:

diff --git a/src/core/getkey.c b/src/core/getkey.c
index 0f0f8b7..0c280d2 100644
--- a/src/core/getkey.c
+++ b/src/core/getkey.c
@@ -76,9 +76,14 @@ int getkey ( unsigned long timeout ) {
  	if ( character != ESC )
  		return character;

+	character = getchar_timeout ( GETKEY_TIMEOUT );
+	if ( character < 0 )
+		return ESC;
+
+	if ( isalpha ( character ) )
+		return ( toupper ( character ) - 'A' + 1 );
+
  	while ( ( character = getchar_timeout ( GETKEY_TIMEOUT ) ) >= 0 ) {
-		if ( character == '[' )
-			continue;
  		if ( isdigit ( character ) ) {
  			n = ( ( n * 10 ) + ( character - '0' ) );
  			continue;

which should allow you to emulate Ctrl-<key> by pressing ESC,<key> (with 
less than 0.25s between ESC and the other key).

Michael

**Comment by dreamcat4** [comment]
@ipxe-devel @mcb30 

Hello.

* Today have tested your above ^^ keyboard patch today and it worked.
* The ESC key can now act as an alternative to CTRL
* Maybe also condider to be giving a small hint to the user.

For example it currently says:

"Press ctrl-c to exit"

Maybe ammend that to say something like:

"Press ctrl-c or esc-c to exit"

Anyway its very good. Thank you. Please commit / merge.

2.

Also as discussed on IRC, please think to disable this CRYPTO_80211_* in the UEFI build:

https://github.com/dreamcat4/docker-images/blob/master/linux-bin/ipxe/nocrypto/general.h

To avoid the un-needed 20 seconds of boot delay for users of mainstream products such as Gigabyte etc. (for the gathering entropy).

Many thanks.

**Pull request closed without merging**
