### PR TITLE
This change respects $CC

### PR DESCRIPTION
**Pull request by dyeske**
This is an updated patch to respect $CC

### CODE REVIEW

**Comment by caspChristian** [comment]
Please rebase on top of master to try and get rid of the incorrect commits. then push again.
Do not push anything to a PR branch before verifying contents with git log -p

Also do not open new PRs for the same thing.

What is the actual goal of the original patch?

**Comment by NiKiZe** [comment]
Please rebase on top of master to try and get rid of the incorrect commits. then push again.
Do not push anything to a PR branch before verifying contents with git log -p

Also do not open new PRs for the same thing.

What is the actual goal of the original patch?

**Comment by stappersg** [comment]
```
Summary: Prevent dangling merge requests
```

> What is the actual goal of the original patch?

If I recall correct is this change needed for a BSD system (  FreeBSD, NetBSD, OpenBSD ... )

I recomment a  git commit message like

```text
[build] Respect $CC

On BSD systems is `gcc` not the default compiler.
But `$CC` is honored.
```
Additional information on that commit message advice
* Context of git commit messages is `git log`
* Leave out all  _github.com references_,  think *git* (not *github*)
* Leave out references of previous attempts

> Also do not open new PRs for the same thing.

New merge requests are quick way to clean up polluted ones.
As done in #589 and #576.

> Please `git rebase` on top of master to try and get rid of the incorrect commits. then `git push` again.
> Do not push anything to a _PR branch_ before verifying contents with `git log -p`

What I would like to see more, is clear and blunt feedback on merge requests.
Having an canned reply like
> This MR has been closed after review.
> This copy and paste reply has no text on the exact why for the close.
> 
> You, author of the merge request, now know that this attempt was not good enough.
> We, iPXE MR reviewers, now can focus on other iPXE work (like using it ;-)

would help.

Suggestion for another canned reply
> Commit message has no "why"
> 
> Do `git log` and check `mcb30@ipxe.org` commits for good examples of commit messages
> Edit the commit message with `git commit --amend`
> add the why
> do another `git push` of the _git branch_


Dangling merge request do drain human energy. For the submitter due dealing with expectations. For the reviewers due procrastination.  An example of an issue that is harming the iPXE is the dragging on of #484.

Please close more stuff, because that enables progress.

**Comment by stappersg** [comment]
@dyeske please try again

**Comment by dyeske** [comment]
closing and trying againt

**Comment by dyeske** [comment]
OK new one is here https://github.com/ipxe/ipxe/pull/697

**Pull request closed without merging**
