### PR TITLE
[intelxl] Add PCIID for i40e (Fixes #653)

### LINKED ISSUE #653: Additional PCI ID for intelxl (aka i40e)?
A customer of ours was trying to iPXE boot (using the TritonDataCenter downstream `ipxe`) on a machine equipped with X710s with the PCI ID of 8086,15ff, and the machine would reboot before iPXE handed off control to illumos.  There is no entry for that in the intelxl.c file.  We need to be sure, but adding the line (per https://github.com/TritonDataCenter/ipxe/pull/11) may be all we needed.

### PR DESCRIPTION
**Pull request by danmcd**
We're testing this in our own downstream (see https://github.com/TritonDataCenter/ipxe/pull/11), and will confirm our customer's "Yes it works," feedback.

### CODE REVIEW

**Comment by danmcd** [comment]
Regression test passed using this patch on our downstream to boot both an i40e/X710 (existing PCI ID) and an ixgbe/X540 (for non-i40e regression). Customer (who uses the new PCI ID) feedback will arrive later this week.

**Comment by NiKiZe** [comment]
Thanks for the PR, We should wait for the Customer to verify before doing more.
Please edit PR message and add "Fix #653" To automatically close that issue when this is merged

If possible update git commit message to follow syntax of other commits where PCIids have been added.
Suggestion: `[intelxl] Add PCIID for i40e`
And then force push to same branch to update this PR

**Comment by danmcd** [comment]
Please ACK or NAK that I've addressed your concerns with the commit message and PR summary.

**Comment by NiKiZe** [comment]
> Please ACK or NAK that I've addressed your concerns with the commit message and PR summary.

Looks good, thanks

**Comment by NiKiZe** [comment]
Since this was confirmed working in https://github.com/ipxe/ipxe/issues/653#issuecomment-1171502166 we should be confident in merging this @mcb30

**Comment by danmcd** [comment]
You folks taking this back?

**Comment by NiKiZe** [comment]
Once time exists to handle, this will probably be merged.

**Comment by danmcd** [comment]
(Just wanted to make sure I didn't miss anything else.  No more from me, thanks!)

**Review by stappersg — APPROVED** [review]
Merging this will help those with `8086:1599` devices, others are not effected.  So netto an improvement for _iPXE_.

**Review by stappersg — APPROVED** [review]
Merging this will help those with `8086:1599` devices, others are not effected.  So netto an improvement for _iPXE_.

**Comment by mcb30** [comment]
I'm very unconvinced that this works, since 8086:1599 is a PCI ID for the 100Gig (`ice`) driver, not the 40Gig (`i40e`) driver.

I'm expecting to merge the iPXE driver for the 100Gig family this week, which will include the 8086:1599 device ID for that driver.

**Comment by danmcd** [comment]
Whoa.  This is supposed to be 15ff... not 1599.  I'm so sorry.

**Comment by danmcd** [comment]
https://pci-ids.ucw.cz/read/PC/8086/15ff

**Comment by mcb30** [comment]
@danmcd Thanks for clarifying the typo! Closing since the fixed-up change is already now present in https://github.com/ipxe/ipxe/commit/9dfcdc04c86503924e1424757082d07e3649f59e

**Pull request closed without merging**
