### PR TITLE
allow to build ISO image with EFI support (ipxe.eiso)

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by ipxe-devel** [comment]
On 15/03/16 13:33, Christian Hesse wrote:
>   * allow to build ISO image with EFI support (ipxe.eiso)

It's a really nice feature to have, but this patch doesn't correctly 
express the dependencies.  There's nothing that would cause the .efi 
files to be built before the geniso script tried to incorporate them 
into the ISO image.

A correct solution would need to take into account the way that iPXE 
spins up one make subprocess per $(BIN) directory.  See the "More than 
one BIN directory was specified..." block in Makefile.housekeeping. 
We'd need to find a (clean) way to wait for the make subprocesses to 
complete before building any multi-BIN targets.

If we can find a clean solution to this, that would be great and I would 
happily add targets for combined ROM images (via util/catrom.pl), 
combined ISOs, combined USB keys, etc.

Michael

**Comment by eworm-de** [comment]
Ah, true...

Looks like I just built in the correct order for things to work correctly. :-D
I will have a look at the build system.

**Comment by eworm-de** [comment]
For those who want to try... Build with:
```
make bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin/ipxe.eiso
```

**Comment by habetsm** [comment]
> A correct solution would need to take into account the way that iPXE
> spins up one make subprocess per $(BIN) directory. See the "More than
> one BIN directory was specified..." block in Makefile.housekeeping.
> We'd need to find a (clean) way to wait for the make subprocesses to
> complete before building any multi-BIN targets.

I wonder if this can be achieved using:
.NOTPARALLEL: bin/blib.a $(BIN_GOALS_FIRST) $(BIN_GOALS_OTHER)

**Comment by champtar** [comment]
I have no Makefile skills to help finish this PR, but thanks @eworm-de, it's working perfectly with your example command
(I've tested BIOS/UEFI cdrom/disk under QEMU/KVM)

**Comment by aarnaud** [comment]
I think, an other PR was made and merge.
I can now build EFI iso
```
make -C src bin-x86_64-efi/ipxe.iso
```

**Comment by q2dg** [comment]
> I think, an other PR was made and merge.
> I can now build EFI iso
> 
> ```
> make -C src bin-x86_64-efi/ipxe.iso
> ```

I get the error 

util/genfsimg: could not find isolinux.bin
make: *** [Makefile.efi:54: bin-x86_64-efi/ipxe.iso] Error 1

**Comment by aarnaud** [comment]
Missing dependency to build : `isolinux`  https://packages.ubuntu.com/bionic/all/isolinux/filelist

**Comment by q2dg** [comment]
Thanks. For completeness, I've found "isolinux.bin" file inside "syslinux-nonlinux" package in Fedora systems (I use that distro).

**Comment by aarnaud** [comment]
If it working for you this issue can be closed

**Comment by q2dg** [comment]
Thanks. Iso has been created succefully but I haven't been able to boot any EFI VirtualBox machine with it.
Maybe it's a VirtualBox fault, I don't know, I must try in a real machine to confirm
Anyway, thanks a lot for your guiding

P.S: (I can't close the issue, I'm not its creator)

**Comment by aarnaud** [comment]
you can also try my iso image here : https://github.com/aarnaud/ipxe/releases/tag/v1.21.1-https

**Comment by q2dg** [comment]
Thanks! But it happens the same. There's must be something wrong with EFI's implementation in VirtualBox. Never mind!! Thanks a lot

Captura de 2021-03-20 17-34-40

**Comment by aarnaud** [comment]
I tested with virt-manager

**Comment by ipxe-devel** [comment]
On Sat, Mar 20, 2021 at 02:35:18AM -0700, Osqui LittleRiver wrote:
> 
> I can't close the issue, I'm not its creator
> 

@eworm-de or others who can, please do

**Comment by eworm-de** [comment]
This is now obsolete, so closing.

**Comment by champtar** [comment]
Relevant PR: #204

**Comment by champtar** [comment]
And with the addition of a3f1e8fb6707811e6eb90e339d7ebe813fd89a63, here how to build BIOS/UEFI ISO/USB/...
```
make bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin/ipxe.lkrn
./util/genfsimg -o my.iso -s script.ipxe bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin/ipxe.lkrn
```

**Comment by q2dg** [comment]
Could it be possible to add a link in dowloads's main site page to a prebuilt iso with uefi support like there´s already one to a prebuilt iso with bios support? I mean...put in https://www.ipxe.org/download a pharagraph like: 

"You can download a prebuilt binary version of iPXE as an ISO image from http://boot.ipxe.org/ipxe.iso **(for BIOS systems) and from http://xxxxxx (for UEFI systems). These images** allow you to experiment with iPXE for the first time. To use iPXE fully, you will need to build an appropriate image from source."

Thanks a lot!

**Comment by NiKiZe** [comment]
I don't see a need for both, one iso with both should be fine?

**Comment by q2dg** [comment]
Of course!

**Pull request closed without merging**
