### PR TITLE
[bnxt] Update driver source files to latest internal versions

### PR DESCRIPTION
**Pull request by jw14812**
[bnxt] Updated driver source files to latest internal versions

### CODE REVIEW

**Comment by ipxe-devel** [comment]
On Tue, Jun 30, 2020 at 01:28:18PM -0700, jw14812 wrote:
> 
>   https://github.com/ipxe/ipxe/pull/118
> 


This branch has conflicts that must be resolved

Conflicting files
src/drivers/net/bnxt/bnxt.c
src/drivers/net/bnxt/bnxt.h
src/drivers/net/bnxt/bnxt_dbg.h

**Comment by jw14812** [comment]
Hi Michael, I wanted to check if this commit was ready to be merged, or if there is anything further I needed to address? We have gotten a request from customer to add bnxt component into the Makefile, so that it is included in the images.  I wanted to check if this could be merged before I create a pull request the change to the Makefile. Thanks

**Comment by dimsua** [comment]
Hi.
I have trying this build, but ipxe have error "No more network devices"
In debug:
Java_iKVM_Viewer_v1 69 40_185 48 251 247__-_Resolution_720_X_400_-_FPS_2_2021-05-07_14-40-26

**Comment by stappersg** [comment]
Text from https://lists.ipxe.org/pipermail/ipxe-devel/2023-January/007592.html

> The bnxt driver (authored by Broadcom) has very few comments and includes a _lot_ of unnecessary code (14000 lines for bnxt compared to 3000 lines for the comparable intelxl driver). I wouldn't even want to start debugging it remotely.  You are very welcome to have a go!
>
> For future reference, in case anyone else finding this thread has hit problems with bnxt in iPXE and does need to be able to boot from it: the iPXE bnxt driver should probably be rewritten in its entirety to be much smaller and simpler.
>
> Thanks,
>
> Michael



My request is to **close this merge request**. Either by merging it or just by closing the MR. Both ways approaches express the same sentiment as the current state of this issue (ignored for more as twenty month): **We don't care about the bnxt driver**. For the _iPXE project_ would the benefit no more energy drain on this dangling MR.

**Pull request closed without merging**
