### PR TITLE
[netdevice] Add ll-protocol setting

### PR DESCRIPTION
**Pull request by Porsh33**
Add a new setting that allows using "netdev->ll-protocol" property in scripts. This can be useful in order to skip configuring interfaces using their link layer protocol or, conversely, configure only selected interface type (Ethernet, IPoIB, etc.)

Example script:
```
set idx:int32 0
:loop
isset ${net${idx}/mac} || exit 0
iseq ${net${idx}/ll-protocol} IPoIB && goto try_next ||
autoboot net${idx} ||
:try_next
inc idx && goto loop
```

### CODE REVIEW

**Comment by stappersg** [comment]
(to express that the merge request got human attention)

In the _iPXE script_ is
```text
iseq ${net${idx}/ll-protocol} IPoIB
```

What defined `IPoIB`?

**Comment by Porsh33** [comment]
As i realised, there are three options currently supported:  `Ethernet, 802.11, IPoIB`

https://github.com/search?q=repo%3Aipxe%2Fipxe+struct+ll_protocol+__ll_protocol&type=code

**Comment by stappersg** [comment]
Accidental close?

image

**Comment by Porsh33** [comment]
> Accidental close?
> 
Yes, unsuccessful attempt to rebase my fork. I think I'll create new branch in my fork, make new PR out of it and refer to this discussion

**Pull request closed without merging**
