### PR TITLE
[bnxt] Reorder PCI device ID matrix

### PR DESCRIPTION
**Pull request by jw14812**
Reorder PCI device ID matrix in ascending order for easier readability.

Signed-off-by: Joseph Wong <joseph.wong@broadcom.com>

### CODE REVIEW

**Review by stappersg — COMMENTED** [review]
Looks good

**Comment by mcb30** [comment]
Thanks.  See comment in https://github.com/ipxe/ipxe/pull/1145#issuecomment-1941363113

**Comment by stappersg** [comment]
@jw14812 seems to have missed previous comment. And also #1158.


Hello Joseph,

Please help the iPXE project by closing this merge request.  The gain of your action is that no further human energy is spend^Wlost on an outdated MR.

**Comment by mcb30** [comment]
My fault, sorry - I meant to close this when the replacement PR was merged.

**Pull request closed without merging**
