### PR TITLE
[intel] Add PCI ID for I219-V and -LM 10 to 15

### PR DESCRIPTION
**Pull request by NiKiZe**
Signed-off-by: Christian Nilsson <nikize@gmail.com>

### CODE REVIEW

**Comment by NiKiZe** [comment]
In Regards to testing:
i219v-13 link detection a bit slow on gig, both gig and 100mbit speed ok, up/down change detected
Download speed might actually be better on NII
100Mbit link, with download started, and switched to gig, was perceived to continue on 100Mbit speed and not gig. (no hard numbers or other tests where done here)
Tested on a Lenovo T15 Gen 2

i219lm-7 100mbit tested ok

Other devices has not been tested, but experience says that the driver does not need any other changes to work on newer machines.

**Comment by srett** [comment]
Nice, just wanted to open a PR for `i219lm-11` – tested and confirmed working on a GBit link :)

**Comment by NiKiZe** [comment]
I can now also add V-10 to the list of actually tested devices

**Review by mcb30 — APPROVED** [review]

**Comment by mcb30** [comment]
@NiKiZe Merged - thanks for keeping these up to date!

**Pull request merged**
