### PR TITLE
[PATCH] [intel] Add PCI ID for I219-V and -LM 16,17

### PR DESCRIPTION
**Pull request by NiKiZe**

### CODE REVIEW

**Comment by NiKiZe** [comment]
Only 0x1a1f was tested on Thinkpad 21AH0091MX, but only in EFI mode.
Windows driver used is the same e1d68x64.inf as previous NICs as well.

Non scientific observation was that the NII driver seemed slightly faster then iPXE native driver, I think I have noticed this on previous changes as well, but I still think it is better to have them in iPXE for USB boot or similar.

Experience also says that there is no reason to believe that there will be any issues in PCBIOS mode.

**Comment by stappersg** [comment]
The _diff_ looks good, the _commit message_ should get the content from https://github.com/ipxe/ipxe/pull/770#issuecomment-1273648208.

**Comment by chelmuth** [comment]
I was about to open a PR for e47175678e5f1600f9cfc844e73578782b64141a but discovered this issue. Thus, I can confirm that I219-LM (16) works reliably on Fujitsu LIFEBOOK U7412.

**Comment by mcb30** [comment]
Merged: thanks @NiKiZe and @chelmuth

**Pull request merged**
