### PR TITLE
Add docker build container

### PR DESCRIPTION
**Pull request by Makeshift**
Adds an option to build using Docker, bypassing requirements to install dependencies and the like on the host.

### CODE REVIEW

**Comment by mcb30** [comment]
Thank you for the contribution.  I fundamentally disagree with the idea of projects providing any kind of custom build environment since it encourages the use of non-standard toolchains, and so this will not be merged.

**Comment by berlin4apk** [comment]
Is it possible to add a check for ALL the packages and libs to the makefile?

With a check at the beginning, 
as it is on a new OS installation, time consuming to remember all needed libs and tools. In combination of all the different build targets / settings

**Comment by berlin4apk** [comment]
Or at least keep the list up-to-date in the readme file,
Draft PR https://github.com/ipxe/ipxe/pull/531
Feedback are welcome

**Comment by Makeshift** [comment]
> Thank you for the contribution. I fundamentally disagree with the idea of projects providing any kind of custom build environment since it encourages the use of non-standard toolchains, and so this will not be merged.

Fair enough. My build environment was missing some of the dependencies and I couldn't find a dependency list, so I got stuck in the run-and-see-what-errors loop for a little bit. I just wanted to save others the hassle.

**Comment by NiKiZe** [comment]
> > Thank you for the contribution. I fundamentally disagree with the idea of projects providing any kind of custom build environment since it encourages the use of non-standard toolchains, and so this will not be merged.
> 
> Fair enough. My build environment was missing some of the dependencies and I couldn't find a dependency list, so I got stuck in the run-and-see-what-errors loop for a little bit. I just wanted to save others the hassle.

https://ipxe.org/download#source_code has a list

**Comment by Makeshift** [comment]
> https://ipxe.org/download#source_code has a list

Ah, I didn't see it, thanks!

**Pull request closed without merging**
